spring:
  application:
    name: movie-finder
  r2dbc:
    url: r2dbc:h2:mem:///moviesdb;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    initialisation-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
